# Generated by Django 4.2.15 on 2024-08-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['token', 'updated'], name='myapp_ticke_token_b602ce_idx'),
        ),
    ]
