# Generated by Django 4.2.15 on 2024-08-29 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ticket_myapp_ticke_token_b602ce_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='myapp_ticke_token_b602ce_idx',
        ),
    ]
